apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "devices-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/host
    secretKey: REDIS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/url
    secretKey: REDIS_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/redis/password
    secretKey: REDIS_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/smartcar/client_id
    secretKey: SMARTCAR_CLIENT_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/smartcar/client_secret
    secretKey: SMARTCAR_CLIENT_SECRET
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/smartcar/webhook_id
    secretKey: SMARTCAR_WEBHOOK_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/smartcar/management_token
    secretKey: SMARTCAR_MANAGEMENT_TOKEN
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/appsearch/host
    secretKey: ELASTIC_SEARCH_APP_SEARCH_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/appsearch/token
    secretKey: ELASTIC_SEARCH_APP_SEARCH_TOKEN
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/enrich_status/host
    secretKey: ELASTIC_SEARCH_ENRICH_STATUS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/enrich_status/username
    secretKey: ELASTIC_SEARCH_ENRICH_STATUS_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/enrich_status/password
    secretKey: ELASTIC_SEARCH_ENRICH_STATUS_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/credentials-encryption/kms/keyid
    secretKey: KMS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/credentials-encryption/keyid
    secretKey: AWS_ACCESS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/credentials-encryption/accesskey
    secretKey: AWS_SECRET_ACCESS_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/autopi/management_token
    secretKey: AUTO_PI_API_TOKEN
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/autopi/management_url
    secretKey: AUTO_PI_API_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/documents/s3/keyid
    secretKey: DOCUMENTS_AWS_ACCESS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/documents/s3/accesskey
    secretKey: DOCUMENTS_AWS_SECRET_ACCESS_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/nft/s3/access_key_id
    secretKey: NFT_AWS_ACCESS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/nft/s3/secret_access_key
    secretKey: NFT_AWS_SECRET_ACCESS_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/drivly/apikey
    secretKey: DRIVLY_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/devices-api/google/maps-api-key
    secretKey: GOOGLE_MAPS_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/vincario/apikey
    secretKey: VINCARIO_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/definitions/vincario/apisecret
    secretKey: VINCARIO_API_SECRET
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/openai/secret_key
    secretKey: OPENAI_SECRET_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/vc/vin/issuer_private_key
    secretKey: ISSUER_PRIVATE_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/tesla/client_id
    secretKey: TESLA_CLIENT_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/tesla/client_secret
    secretKey: TESLA_CLIENT_SECRET
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/ethereum/rpc_url
    secretKey: MAIN_RPC_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/clickhouse/host
    secretKey: CLICKHOUSE_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/clickhouse/user
    secretKey: CLICKHOUSE_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/clickhouse/pass
    secretKey: CLICKHOUSE_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/cio/api_key
    secretKey: CUSTOMER_IO_API_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "devices-api.fullname" . }}-secret
    template:
      metadata: {}
