// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/grpc/tesla.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPollingInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollingInfoRequest) Reset() {
	*x = GetPollingInfoRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollingInfoRequest) ProtoMessage() {}

func (x *GetPollingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPollingInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{0}
}

func (x *GetPollingInfoRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetPollingInfoResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DiscountedData        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=discounted_data,json=discountedData,proto3" json:"discounted_data,omitempty"`
	FleetTelemetryCapable *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=fleet_telemetry_capable,json=fleetTelemetryCapable,proto3" json:"fleet_telemetry_capable,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetPollingInfoResponse) Reset() {
	*x = GetPollingInfoResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollingInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollingInfoResponse) ProtoMessage() {}

func (x *GetPollingInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollingInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPollingInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{1}
}

func (x *GetPollingInfoResponse) GetDiscountedData() *wrapperspb.BoolValue {
	if x != nil {
		return x.DiscountedData
	}
	return nil
}

func (x *GetPollingInfoResponse) GetFleetTelemetryCapable() *wrapperspb.BoolValue {
	if x != nil {
		return x.FleetTelemetryCapable
	}
	return nil
}

type GetFleetStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId int64                  `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFleetStatusRequest) Reset() {
	*x = GetFleetStatusRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatusRequest) ProtoMessage() {}

func (x *GetFleetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFleetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{2}
}

func (x *GetFleetStatusRequest) GetVehicleTokenId() int64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type GetFleetStatusResponse struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	KeyPaired                          bool                   `protobuf:"varint,1,opt,name=key_paired,json=keyPaired,proto3" json:"key_paired,omitempty"`
	FirmwareVersion                    string                 `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	VehicleCommandProtocolRequired     bool                   `protobuf:"varint,3,opt,name=vehicle_command_protocol_required,json=vehicleCommandProtocolRequired,proto3" json:"vehicle_command_protocol_required,omitempty"`
	DiscountedDeviceData               bool                   `protobuf:"varint,4,opt,name=discounted_device_data,json=discountedDeviceData,proto3" json:"discounted_device_data,omitempty"`
	FleetTelemetryVersion              string                 `protobuf:"bytes,5,opt,name=fleet_telemetry_version,json=fleetTelemetryVersion,proto3" json:"fleet_telemetry_version,omitempty"`
	SafetyScreenStreamingToggleEnabled *bool                  `protobuf:"varint,6,opt,name=safety_screen_streaming_toggle_enabled,json=safetyScreenStreamingToggleEnabled,proto3,oneof" json:"safety_screen_streaming_toggle_enabled,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *GetFleetStatusResponse) Reset() {
	*x = GetFleetStatusResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatusResponse) ProtoMessage() {}

func (x *GetFleetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFleetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{3}
}

func (x *GetFleetStatusResponse) GetKeyPaired() bool {
	if x != nil {
		return x.KeyPaired
	}
	return false
}

func (x *GetFleetStatusResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *GetFleetStatusResponse) GetVehicleCommandProtocolRequired() bool {
	if x != nil {
		return x.VehicleCommandProtocolRequired
	}
	return false
}

func (x *GetFleetStatusResponse) GetDiscountedDeviceData() bool {
	if x != nil {
		return x.DiscountedDeviceData
	}
	return false
}

func (x *GetFleetStatusResponse) GetFleetTelemetryVersion() string {
	if x != nil {
		return x.FleetTelemetryVersion
	}
	return ""
}

func (x *GetFleetStatusResponse) GetSafetyScreenStreamingToggleEnabled() bool {
	if x != nil && x.SafetyScreenStreamingToggleEnabled != nil {
		return *x.SafetyScreenStreamingToggleEnabled
	}
	return false
}

type GetFleetTelemetryConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId int64                  `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFleetTelemetryConfigRequest) Reset() {
	*x = GetFleetTelemetryConfigRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetTelemetryConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetTelemetryConfigRequest) ProtoMessage() {}

func (x *GetFleetTelemetryConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetTelemetryConfigRequest.ProtoReflect.Descriptor instead.
func (*GetFleetTelemetryConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{4}
}

func (x *GetFleetTelemetryConfigRequest) GetVehicleTokenId() int64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type GetFleetTelemetryConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Synced        bool                   `protobuf:"varint,1,opt,name=synced,proto3" json:"synced,omitempty"`
	Configured    bool                   `protobuf:"varint,2,opt,name=configured,proto3" json:"configured,omitempty"`
	LimitReached  bool                   `protobuf:"varint,3,opt,name=limit_reached,json=limitReached,proto3" json:"limit_reached,omitempty"`
	KeyPaired     bool                   `protobuf:"varint,4,opt,name=key_paired,json=keyPaired,proto3" json:"key_paired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFleetTelemetryConfigResponse) Reset() {
	*x = GetFleetTelemetryConfigResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetTelemetryConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetTelemetryConfigResponse) ProtoMessage() {}

func (x *GetFleetTelemetryConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetTelemetryConfigResponse.ProtoReflect.Descriptor instead.
func (*GetFleetTelemetryConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{5}
}

func (x *GetFleetTelemetryConfigResponse) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *GetFleetTelemetryConfigResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *GetFleetTelemetryConfigResponse) GetLimitReached() bool {
	if x != nil {
		return x.LimitReached
	}
	return false
}

func (x *GetFleetTelemetryConfigResponse) GetKeyPaired() bool {
	if x != nil {
		return x.KeyPaired
	}
	return false
}

type ConfigureFleetTelemetryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId int64                  `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureFleetTelemetryRequest) Reset() {
	*x = ConfigureFleetTelemetryRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureFleetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureFleetTelemetryRequest) ProtoMessage() {}

func (x *ConfigureFleetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureFleetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*ConfigureFleetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigureFleetTelemetryRequest) GetVehicleTokenId() int64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type ConfigureFleetTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureFleetTelemetryResponse) Reset() {
	*x = ConfigureFleetTelemetryResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureFleetTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureFleetTelemetryResponse) ProtoMessage() {}

func (x *ConfigureFleetTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureFleetTelemetryResponse.ProtoReflect.Descriptor instead.
func (*ConfigureFleetTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{7}
}

type RemoveFleetTelemetryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId int64                  `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveFleetTelemetryRequest) Reset() {
	*x = RemoveFleetTelemetryRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFleetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFleetTelemetryRequest) ProtoMessage() {}

func (x *RemoveFleetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFleetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*RemoveFleetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFleetTelemetryRequest) GetVehicleTokenId() int64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type RemoveFleetTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFleetTelemetryResponse) Reset() {
	*x = RemoveFleetTelemetryResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFleetTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFleetTelemetryResponse) ProtoMessage() {}

func (x *RemoveFleetTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFleetTelemetryResponse.ProtoReflect.Descriptor instead.
func (*RemoveFleetTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{9}
}

type GetScopesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId int64                  `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetScopesRequest) Reset() {
	*x = GetScopesRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScopesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScopesRequest) ProtoMessage() {}

func (x *GetScopesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScopesRequest.ProtoReflect.Descriptor instead.
func (*GetScopesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{10}
}

func (x *GetScopesRequest) GetVehicleTokenId() int64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type GetScopesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scopes        []string               `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScopesResponse) Reset() {
	*x = GetScopesResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScopesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScopesResponse) ProtoMessage() {}

func (x *GetScopesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScopesResponse.ProtoReflect.Descriptor instead.
func (*GetScopesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{11}
}

func (x *GetScopesResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type StopTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId int64                  `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{12}
}

func (x *StopTaskRequest) GetVehicleTokenId() int64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{13}
}

type StartTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleTokenId int64                  `protobuf:"varint,1,opt,name=vehicle_token_id,json=vehicleTokenId,proto3" json:"vehicle_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{14}
}

func (x *StartTaskRequest) GetVehicleTokenId() int64 {
	if x != nil {
		return x.VehicleTokenId
	}
	return 0
}

type StartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskResponse) Reset() {
	*x = StartTaskResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskResponse) ProtoMessage() {}

func (x *StartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskResponse.ProtoReflect.Descriptor instead.
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{15}
}

var File_pkg_grpc_tesla_proto protoreflect.FileDescriptor

const file_pkg_grpc_tesla_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/grpc/tesla.proto\x12\x05tesla\x1a\x1egoogle/protobuf/wrappers.proto\"0\n" +
	"\x15GetPollingInfoRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xb1\x01\n" +
	"\x16GetPollingInfoResponse\x12C\n" +
	"\x0fdiscounted_data\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x0ediscountedData\x12R\n" +
	"\x17fleet_telemetry_capable\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x15fleetTelemetryCapable\"A\n" +
	"\x15GetFleetStatusRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\x03R\x0evehicleTokenId\"\x9f\x03\n" +
	"\x16GetFleetStatusResponse\x12\x1d\n" +
	"\n" +
	"key_paired\x18\x01 \x01(\bR\tkeyPaired\x12)\n" +
	"\x10firmware_version\x18\x02 \x01(\tR\x0ffirmwareVersion\x12I\n" +
	"!vehicle_command_protocol_required\x18\x03 \x01(\bR\x1evehicleCommandProtocolRequired\x124\n" +
	"\x16discounted_device_data\x18\x04 \x01(\bR\x14discountedDeviceData\x126\n" +
	"\x17fleet_telemetry_version\x18\x05 \x01(\tR\x15fleetTelemetryVersion\x12W\n" +
	"&safety_screen_streaming_toggle_enabled\x18\x06 \x01(\bH\x00R\"safetyScreenStreamingToggleEnabled\x88\x01\x01B)\n" +
	"'_safety_screen_streaming_toggle_enabled\"J\n" +
	"\x1eGetFleetTelemetryConfigRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\x03R\x0evehicleTokenId\"\x9d\x01\n" +
	"\x1fGetFleetTelemetryConfigResponse\x12\x16\n" +
	"\x06synced\x18\x01 \x01(\bR\x06synced\x12\x1e\n" +
	"\n" +
	"configured\x18\x02 \x01(\bR\n" +
	"configured\x12#\n" +
	"\rlimit_reached\x18\x03 \x01(\bR\flimitReached\x12\x1d\n" +
	"\n" +
	"key_paired\x18\x04 \x01(\bR\tkeyPaired\"J\n" +
	"\x1eConfigureFleetTelemetryRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\x03R\x0evehicleTokenId\"!\n" +
	"\x1fConfigureFleetTelemetryResponse\"G\n" +
	"\x1bRemoveFleetTelemetryRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\x03R\x0evehicleTokenId\"\x1e\n" +
	"\x1cRemoveFleetTelemetryResponse\"<\n" +
	"\x10GetScopesRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\x03R\x0evehicleTokenId\"+\n" +
	"\x11GetScopesResponse\x12\x16\n" +
	"\x06scopes\x18\x01 \x03(\tR\x06scopes\";\n" +
	"\x0fStopTaskRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\x03R\x0evehicleTokenId\"\x12\n" +
	"\x10StopTaskResponse\"<\n" +
	"\x10StartTaskRequest\x12(\n" +
	"\x10vehicle_token_id\x18\x01 \x01(\x03R\x0evehicleTokenId\"\x13\n" +
	"\x11StartTaskResponse2\x9e\x05\n" +
	"\fTeslaService\x12M\n" +
	"\x0eGetPollingInfo\x12\x1c.tesla.GetPollingInfoRequest\x1a\x1d.tesla.GetPollingInfoResponse\x12M\n" +
	"\x0eGetFleetStatus\x12\x1c.tesla.GetFleetStatusRequest\x1a\x1d.tesla.GetFleetStatusResponse\x12h\n" +
	"\x17GetFleetTelemetryConfig\x12%.tesla.GetFleetTelemetryConfigRequest\x1a&.tesla.GetFleetTelemetryConfigResponse\x12h\n" +
	"\x17ConfigureFleetTelemetry\x12%.tesla.ConfigureFleetTelemetryRequest\x1a&.tesla.ConfigureFleetTelemetryResponse\x12_\n" +
	"\x14RemoveFleetTelemetry\x12\".tesla.RemoveFleetTelemetryRequest\x1a#.tesla.RemoveFleetTelemetryResponse\x12>\n" +
	"\tGetScopes\x12\x17.tesla.GetScopesRequest\x1a\x18.tesla.GetScopesResponse\x12;\n" +
	"\bStopTask\x12\x16.tesla.StopTaskRequest\x1a\x17.tesla.StopTaskResponse\x12>\n" +
	"\tStartTask\x12\x17.tesla.StartTaskRequest\x1a\x18.tesla.StartTaskResponseB.Z,github.com/DIMO-Network/devices-api/pkg/grpcb\x06proto3"

var (
	file_pkg_grpc_tesla_proto_rawDescOnce sync.Once
	file_pkg_grpc_tesla_proto_rawDescData []byte
)

func file_pkg_grpc_tesla_proto_rawDescGZIP() []byte {
	file_pkg_grpc_tesla_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_tesla_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_proto_rawDesc), len(file_pkg_grpc_tesla_proto_rawDesc)))
	})
	return file_pkg_grpc_tesla_proto_rawDescData
}

var file_pkg_grpc_tesla_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_grpc_tesla_proto_goTypes = []any{
	(*GetPollingInfoRequest)(nil),           // 0: tesla.GetPollingInfoRequest
	(*GetPollingInfoResponse)(nil),          // 1: tesla.GetPollingInfoResponse
	(*GetFleetStatusRequest)(nil),           // 2: tesla.GetFleetStatusRequest
	(*GetFleetStatusResponse)(nil),          // 3: tesla.GetFleetStatusResponse
	(*GetFleetTelemetryConfigRequest)(nil),  // 4: tesla.GetFleetTelemetryConfigRequest
	(*GetFleetTelemetryConfigResponse)(nil), // 5: tesla.GetFleetTelemetryConfigResponse
	(*ConfigureFleetTelemetryRequest)(nil),  // 6: tesla.ConfigureFleetTelemetryRequest
	(*ConfigureFleetTelemetryResponse)(nil), // 7: tesla.ConfigureFleetTelemetryResponse
	(*RemoveFleetTelemetryRequest)(nil),     // 8: tesla.RemoveFleetTelemetryRequest
	(*RemoveFleetTelemetryResponse)(nil),    // 9: tesla.RemoveFleetTelemetryResponse
	(*GetScopesRequest)(nil),                // 10: tesla.GetScopesRequest
	(*GetScopesResponse)(nil),               // 11: tesla.GetScopesResponse
	(*StopTaskRequest)(nil),                 // 12: tesla.StopTaskRequest
	(*StopTaskResponse)(nil),                // 13: tesla.StopTaskResponse
	(*StartTaskRequest)(nil),                // 14: tesla.StartTaskRequest
	(*StartTaskResponse)(nil),               // 15: tesla.StartTaskResponse
	(*wrapperspb.BoolValue)(nil),            // 16: google.protobuf.BoolValue
}
var file_pkg_grpc_tesla_proto_depIdxs = []int32{
	16, // 0: tesla.GetPollingInfoResponse.discounted_data:type_name -> google.protobuf.BoolValue
	16, // 1: tesla.GetPollingInfoResponse.fleet_telemetry_capable:type_name -> google.protobuf.BoolValue
	0,  // 2: tesla.TeslaService.GetPollingInfo:input_type -> tesla.GetPollingInfoRequest
	2,  // 3: tesla.TeslaService.GetFleetStatus:input_type -> tesla.GetFleetStatusRequest
	4,  // 4: tesla.TeslaService.GetFleetTelemetryConfig:input_type -> tesla.GetFleetTelemetryConfigRequest
	6,  // 5: tesla.TeslaService.ConfigureFleetTelemetry:input_type -> tesla.ConfigureFleetTelemetryRequest
	8,  // 6: tesla.TeslaService.RemoveFleetTelemetry:input_type -> tesla.RemoveFleetTelemetryRequest
	10, // 7: tesla.TeslaService.GetScopes:input_type -> tesla.GetScopesRequest
	12, // 8: tesla.TeslaService.StopTask:input_type -> tesla.StopTaskRequest
	14, // 9: tesla.TeslaService.StartTask:input_type -> tesla.StartTaskRequest
	1,  // 10: tesla.TeslaService.GetPollingInfo:output_type -> tesla.GetPollingInfoResponse
	3,  // 11: tesla.TeslaService.GetFleetStatus:output_type -> tesla.GetFleetStatusResponse
	5,  // 12: tesla.TeslaService.GetFleetTelemetryConfig:output_type -> tesla.GetFleetTelemetryConfigResponse
	7,  // 13: tesla.TeslaService.ConfigureFleetTelemetry:output_type -> tesla.ConfigureFleetTelemetryResponse
	9,  // 14: tesla.TeslaService.RemoveFleetTelemetry:output_type -> tesla.RemoveFleetTelemetryResponse
	11, // 15: tesla.TeslaService.GetScopes:output_type -> tesla.GetScopesResponse
	13, // 16: tesla.TeslaService.StopTask:output_type -> tesla.StopTaskResponse
	15, // 17: tesla.TeslaService.StartTask:output_type -> tesla.StartTaskResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_grpc_tesla_proto_init() }
func file_pkg_grpc_tesla_proto_init() {
	if File_pkg_grpc_tesla_proto != nil {
		return
	}
	file_pkg_grpc_tesla_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_proto_rawDesc), len(file_pkg_grpc_tesla_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_tesla_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_tesla_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_tesla_proto_msgTypes,
	}.Build()
	File_pkg_grpc_tesla_proto = out.File
	file_pkg_grpc_tesla_proto_goTypes = nil
	file_pkg_grpc_tesla_proto_depIdxs = nil
}
