// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: pkg/grpc/tesla.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPollingInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollingInfoRequest) Reset() {
	*x = GetPollingInfoRequest{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollingInfoRequest) ProtoMessage() {}

func (x *GetPollingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPollingInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{0}
}

func (x *GetPollingInfoRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetPollingInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DiscountedData *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=discounted_data,json=discountedData,proto3" json:"discounted_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPollingInfoResponse) Reset() {
	*x = GetPollingInfoResponse{}
	mi := &file_pkg_grpc_tesla_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollingInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollingInfoResponse) ProtoMessage() {}

func (x *GetPollingInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_tesla_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollingInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPollingInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_tesla_proto_rawDescGZIP(), []int{1}
}

func (x *GetPollingInfoResponse) GetDiscountedData() *wrapperspb.BoolValue {
	if x != nil {
		return x.DiscountedData
	}
	return nil
}

var File_pkg_grpc_tesla_proto protoreflect.FileDescriptor

var file_pkg_grpc_tesla_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x6c, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x65, 0x73, 0x6c, 0x61, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22,
	0x5d, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x32, 0x5d,
	0x0a, 0x0c, 0x54, 0x65, 0x73, 0x6c, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1c, 0x2e, 0x74, 0x65, 0x73, 0x6c, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x74, 0x65, 0x73, 0x6c, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x49, 0x4d, 0x4f,
	0x2d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_grpc_tesla_proto_rawDescOnce sync.Once
	file_pkg_grpc_tesla_proto_rawDescData []byte
)

func file_pkg_grpc_tesla_proto_rawDescGZIP() []byte {
	file_pkg_grpc_tesla_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_tesla_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_proto_rawDesc), len(file_pkg_grpc_tesla_proto_rawDesc)))
	})
	return file_pkg_grpc_tesla_proto_rawDescData
}

var file_pkg_grpc_tesla_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_tesla_proto_goTypes = []any{
	(*GetPollingInfoRequest)(nil),  // 0: tesla.GetPollingInfoRequest
	(*GetPollingInfoResponse)(nil), // 1: tesla.GetPollingInfoResponse
	(*wrapperspb.BoolValue)(nil),   // 2: google.protobuf.BoolValue
}
var file_pkg_grpc_tesla_proto_depIdxs = []int32{
	2, // 0: tesla.GetPollingInfoResponse.discounted_data:type_name -> google.protobuf.BoolValue
	0, // 1: tesla.TeslaService.GetPollingInfo:input_type -> tesla.GetPollingInfoRequest
	1, // 2: tesla.TeslaService.GetPollingInfo:output_type -> tesla.GetPollingInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_grpc_tesla_proto_init() }
func file_pkg_grpc_tesla_proto_init() {
	if File_pkg_grpc_tesla_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_tesla_proto_rawDesc), len(file_pkg_grpc_tesla_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_tesla_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_tesla_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_tesla_proto_msgTypes,
	}.Build()
	File_pkg_grpc_tesla_proto = out.File
	file_pkg_grpc_tesla_proto_goTypes = nil
	file_pkg_grpc_tesla_proto_depIdxs = nil
}
