// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/grpc/tesla.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeslaService_GetPollingInfo_FullMethodName          = "/tesla.TeslaService/GetPollingInfo"
	TeslaService_GetFleetStatus_FullMethodName          = "/tesla.TeslaService/GetFleetStatus"
	TeslaService_GetFleetTelemetryConfig_FullMethodName = "/tesla.TeslaService/GetFleetTelemetryConfig"
	TeslaService_ConfigureFleetTelemetry_FullMethodName = "/tesla.TeslaService/ConfigureFleetTelemetry"
)

// TeslaServiceClient is the client API for TeslaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeslaServiceClient interface {
	GetPollingInfo(ctx context.Context, in *GetPollingInfoRequest, opts ...grpc.CallOption) (*GetPollingInfoResponse, error)
	GetFleetStatus(ctx context.Context, in *GetFleetStatusRequest, opts ...grpc.CallOption) (*GetFleetStatusResponse, error)
	GetFleetTelemetryConfig(ctx context.Context, in *GetFleetTelemetryConfigRequest, opts ...grpc.CallOption) (*GetFleetTelemetryConfigResponse, error)
	ConfigureFleetTelemetry(ctx context.Context, in *ConfigureFleetTelemetryRequest, opts ...grpc.CallOption) (*ConfigureFleetTelemetryResponse, error)
}

type teslaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeslaServiceClient(cc grpc.ClientConnInterface) TeslaServiceClient {
	return &teslaServiceClient{cc}
}

func (c *teslaServiceClient) GetPollingInfo(ctx context.Context, in *GetPollingInfoRequest, opts ...grpc.CallOption) (*GetPollingInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPollingInfoResponse)
	err := c.cc.Invoke(ctx, TeslaService_GetPollingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teslaServiceClient) GetFleetStatus(ctx context.Context, in *GetFleetStatusRequest, opts ...grpc.CallOption) (*GetFleetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFleetStatusResponse)
	err := c.cc.Invoke(ctx, TeslaService_GetFleetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teslaServiceClient) GetFleetTelemetryConfig(ctx context.Context, in *GetFleetTelemetryConfigRequest, opts ...grpc.CallOption) (*GetFleetTelemetryConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFleetTelemetryConfigResponse)
	err := c.cc.Invoke(ctx, TeslaService_GetFleetTelemetryConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teslaServiceClient) ConfigureFleetTelemetry(ctx context.Context, in *ConfigureFleetTelemetryRequest, opts ...grpc.CallOption) (*ConfigureFleetTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureFleetTelemetryResponse)
	err := c.cc.Invoke(ctx, TeslaService_ConfigureFleetTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeslaServiceServer is the server API for TeslaService service.
// All implementations must embed UnimplementedTeslaServiceServer
// for forward compatibility.
type TeslaServiceServer interface {
	GetPollingInfo(context.Context, *GetPollingInfoRequest) (*GetPollingInfoResponse, error)
	GetFleetStatus(context.Context, *GetFleetStatusRequest) (*GetFleetStatusResponse, error)
	GetFleetTelemetryConfig(context.Context, *GetFleetTelemetryConfigRequest) (*GetFleetTelemetryConfigResponse, error)
	ConfigureFleetTelemetry(context.Context, *ConfigureFleetTelemetryRequest) (*ConfigureFleetTelemetryResponse, error)
	mustEmbedUnimplementedTeslaServiceServer()
}

// UnimplementedTeslaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeslaServiceServer struct{}

func (UnimplementedTeslaServiceServer) GetPollingInfo(context.Context, *GetPollingInfoRequest) (*GetPollingInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPollingInfo not implemented")
}
func (UnimplementedTeslaServiceServer) GetFleetStatus(context.Context, *GetFleetStatusRequest) (*GetFleetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFleetStatus not implemented")
}
func (UnimplementedTeslaServiceServer) GetFleetTelemetryConfig(context.Context, *GetFleetTelemetryConfigRequest) (*GetFleetTelemetryConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFleetTelemetryConfig not implemented")
}
func (UnimplementedTeslaServiceServer) ConfigureFleetTelemetry(context.Context, *ConfigureFleetTelemetryRequest) (*ConfigureFleetTelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureFleetTelemetry not implemented")
}
func (UnimplementedTeslaServiceServer) mustEmbedUnimplementedTeslaServiceServer() {}
func (UnimplementedTeslaServiceServer) testEmbeddedByValue()                      {}

// UnsafeTeslaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeslaServiceServer will
// result in compilation errors.
type UnsafeTeslaServiceServer interface {
	mustEmbedUnimplementedTeslaServiceServer()
}

func RegisterTeslaServiceServer(s grpc.ServiceRegistrar, srv TeslaServiceServer) {
	// If the following call pancis, it indicates UnimplementedTeslaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeslaService_ServiceDesc, srv)
}

func _TeslaService_GetPollingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPollingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeslaServiceServer).GetPollingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeslaService_GetPollingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeslaServiceServer).GetPollingInfo(ctx, req.(*GetPollingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeslaService_GetFleetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFleetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeslaServiceServer).GetFleetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeslaService_GetFleetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeslaServiceServer).GetFleetStatus(ctx, req.(*GetFleetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeslaService_GetFleetTelemetryConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFleetTelemetryConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeslaServiceServer).GetFleetTelemetryConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeslaService_GetFleetTelemetryConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeslaServiceServer).GetFleetTelemetryConfig(ctx, req.(*GetFleetTelemetryConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeslaService_ConfigureFleetTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureFleetTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeslaServiceServer).ConfigureFleetTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeslaService_ConfigureFleetTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeslaServiceServer).ConfigureFleetTelemetry(ctx, req.(*ConfigureFleetTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeslaService_ServiceDesc is the grpc.ServiceDesc for TeslaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeslaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tesla.TeslaService",
	HandlerType: (*TeslaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPollingInfo",
			Handler:    _TeslaService_GetPollingInfo_Handler,
		},
		{
			MethodName: "GetFleetStatus",
			Handler:    _TeslaService_GetFleetStatus_Handler,
		},
		{
			MethodName: "GetFleetTelemetryConfig",
			Handler:    _TeslaService_GetFleetTelemetryConfig_Handler,
		},
		{
			MethodName: "ConfigureFleetTelemetry",
			Handler:    _TeslaService_ConfigureFleetTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/tesla.proto",
}
