// Code generated by MockGen. DO NOT EDIT.
// Source: autopi_api_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	services "github.com/DIMO-Network/devices-api/internal/services"
	models "github.com/DIMO-Network/devices-api/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAutoPiAPIService is a mock of AutoPiAPIService interface.
type MockAutoPiAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockAutoPiAPIServiceMockRecorder
}

// MockAutoPiAPIServiceMockRecorder is the mock recorder for MockAutoPiAPIService.
type MockAutoPiAPIServiceMockRecorder struct {
	mock *MockAutoPiAPIService
}

// NewMockAutoPiAPIService creates a new mock instance.
func NewMockAutoPiAPIService(ctrl *gomock.Controller) *MockAutoPiAPIService {
	mock := &MockAutoPiAPIService{ctrl: ctrl}
	mock.recorder = &MockAutoPiAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoPiAPIService) EXPECT() *MockAutoPiAPIServiceMockRecorder {
	return m.recorder
}

// AddDefaultPIDsToTemplate mocks base method.
func (m *MockAutoPiAPIService) AddDefaultPIDsToTemplate(templateID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDefaultPIDsToTemplate", templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDefaultPIDsToTemplate indicates an expected call of AddDefaultPIDsToTemplate.
func (mr *MockAutoPiAPIServiceMockRecorder) AddDefaultPIDsToTemplate(templateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDefaultPIDsToTemplate", reflect.TypeOf((*MockAutoPiAPIService)(nil).AddDefaultPIDsToTemplate), templateID)
}

// ApplyTemplate mocks base method.
func (m *MockAutoPiAPIService) ApplyTemplate(deviceID string, templateID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTemplate", deviceID, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyTemplate indicates an expected call of ApplyTemplate.
func (mr *MockAutoPiAPIServiceMockRecorder) ApplyTemplate(deviceID, templateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTemplate", reflect.TypeOf((*MockAutoPiAPIService)(nil).ApplyTemplate), deviceID, templateID)
}

// AssociateDeviceToTemplate mocks base method.
func (m *MockAutoPiAPIService) AssociateDeviceToTemplate(deviceID string, templateID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssociateDeviceToTemplate", deviceID, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssociateDeviceToTemplate indicates an expected call of AssociateDeviceToTemplate.
func (mr *MockAutoPiAPIServiceMockRecorder) AssociateDeviceToTemplate(deviceID, templateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssociateDeviceToTemplate", reflect.TypeOf((*MockAutoPiAPIService)(nil).AssociateDeviceToTemplate), deviceID, templateID)
}

// CommandQueryVIN mocks base method.
func (m *MockAutoPiAPIService) CommandQueryVIN(ctx context.Context, unitID, deviceID, userDeviceID string) (*services.AutoPiCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandQueryVIN", ctx, unitID, deviceID, userDeviceID)
	ret0, _ := ret[0].(*services.AutoPiCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommandQueryVIN indicates an expected call of CommandQueryVIN.
func (mr *MockAutoPiAPIServiceMockRecorder) CommandQueryVIN(ctx, unitID, deviceID, userDeviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandQueryVIN", reflect.TypeOf((*MockAutoPiAPIService)(nil).CommandQueryVIN), ctx, unitID, deviceID, userDeviceID)
}

// CommandRaw mocks base method.
func (m *MockAutoPiAPIService) CommandRaw(ctx context.Context, unitID, deviceID, command, userDeviceID string) (*services.AutoPiCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandRaw", ctx, unitID, deviceID, command, userDeviceID)
	ret0, _ := ret[0].(*services.AutoPiCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommandRaw indicates an expected call of CommandRaw.
func (mr *MockAutoPiAPIServiceMockRecorder) CommandRaw(ctx, unitID, deviceID, command, userDeviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandRaw", reflect.TypeOf((*MockAutoPiAPIService)(nil).CommandRaw), ctx, unitID, deviceID, command, userDeviceID)
}

// CommandSyncDevice mocks base method.
func (m *MockAutoPiAPIService) CommandSyncDevice(ctx context.Context, unitID, deviceID, userDeviceID string) (*services.AutoPiCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandSyncDevice", ctx, unitID, deviceID, userDeviceID)
	ret0, _ := ret[0].(*services.AutoPiCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommandSyncDevice indicates an expected call of CommandSyncDevice.
func (mr *MockAutoPiAPIServiceMockRecorder) CommandSyncDevice(ctx, unitID, deviceID, userDeviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandSyncDevice", reflect.TypeOf((*MockAutoPiAPIService)(nil).CommandSyncDevice), ctx, unitID, deviceID, userDeviceID)
}

// CreateNewTemplate mocks base method.
func (m *MockAutoPiAPIService) CreateNewTemplate(templateName string, parent int, description string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewTemplate", templateName, parent, description)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewTemplate indicates an expected call of CreateNewTemplate.
func (mr *MockAutoPiAPIServiceMockRecorder) CreateNewTemplate(templateName, parent, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewTemplate", reflect.TypeOf((*MockAutoPiAPIService)(nil).CreateNewTemplate), templateName, parent, description)
}

// GetCommandStatus mocks base method.
func (m *MockAutoPiAPIService) GetCommandStatus(ctx context.Context, jobID string) (*services.AutoPiCommandJob, *models.AutopiJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommandStatus", ctx, jobID)
	ret0, _ := ret[0].(*services.AutoPiCommandJob)
	ret1, _ := ret[1].(*models.AutopiJob)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCommandStatus indicates an expected call of GetCommandStatus.
func (mr *MockAutoPiAPIServiceMockRecorder) GetCommandStatus(ctx, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommandStatus", reflect.TypeOf((*MockAutoPiAPIService)(nil).GetCommandStatus), ctx, jobID)
}

// GetCommandStatusFromAutoPi mocks base method.
func (m *MockAutoPiAPIService) GetCommandStatusFromAutoPi(deviceID, jobID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommandStatusFromAutoPi", deviceID, jobID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommandStatusFromAutoPi indicates an expected call of GetCommandStatusFromAutoPi.
func (mr *MockAutoPiAPIServiceMockRecorder) GetCommandStatusFromAutoPi(deviceID, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommandStatusFromAutoPi", reflect.TypeOf((*MockAutoPiAPIService)(nil).GetCommandStatusFromAutoPi), deviceID, jobID)
}

// GetDeviceByID mocks base method.
func (m *MockAutoPiAPIService) GetDeviceByID(deviceID string) (*services.AutoPiDongleDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByID", deviceID)
	ret0, _ := ret[0].(*services.AutoPiDongleDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByID indicates an expected call of GetDeviceByID.
func (mr *MockAutoPiAPIServiceMockRecorder) GetDeviceByID(deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByID", reflect.TypeOf((*MockAutoPiAPIService)(nil).GetDeviceByID), deviceID)
}

// GetDeviceByUnitID mocks base method.
func (m *MockAutoPiAPIService) GetDeviceByUnitID(unitID string) (*services.AutoPiDongleDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByUnitID", unitID)
	ret0, _ := ret[0].(*services.AutoPiDongleDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByUnitID indicates an expected call of GetDeviceByUnitID.
func (mr *MockAutoPiAPIServiceMockRecorder) GetDeviceByUnitID(unitID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByUnitID", reflect.TypeOf((*MockAutoPiAPIService)(nil).GetDeviceByUnitID), unitID)
}

// GetUserDeviceIntegrationByUnitID mocks base method.
func (m *MockAutoPiAPIService) GetUserDeviceIntegrationByUnitID(ctx context.Context, unitID string) (*models.UserDeviceAPIIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDeviceIntegrationByUnitID", ctx, unitID)
	ret0, _ := ret[0].(*models.UserDeviceAPIIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDeviceIntegrationByUnitID indicates an expected call of GetUserDeviceIntegrationByUnitID.
func (mr *MockAutoPiAPIServiceMockRecorder) GetUserDeviceIntegrationByUnitID(ctx, unitID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDeviceIntegrationByUnitID", reflect.TypeOf((*MockAutoPiAPIService)(nil).GetUserDeviceIntegrationByUnitID), ctx, unitID)
}

// PatchVehicleProfile mocks base method.
func (m *MockAutoPiAPIService) PatchVehicleProfile(vehicleID int, profile services.PatchVehicleProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchVehicleProfile", vehicleID, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchVehicleProfile indicates an expected call of PatchVehicleProfile.
func (mr *MockAutoPiAPIServiceMockRecorder) PatchVehicleProfile(vehicleID, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchVehicleProfile", reflect.TypeOf((*MockAutoPiAPIService)(nil).PatchVehicleProfile), vehicleID, profile)
}

// SetTemplateICEPowerSettings mocks base method.
func (m *MockAutoPiAPIService) SetTemplateICEPowerSettings(templateID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTemplateICEPowerSettings", templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTemplateICEPowerSettings indicates an expected call of SetTemplateICEPowerSettings.
func (mr *MockAutoPiAPIServiceMockRecorder) SetTemplateICEPowerSettings(templateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTemplateICEPowerSettings", reflect.TypeOf((*MockAutoPiAPIService)(nil).SetTemplateICEPowerSettings), templateID)
}

// UnassociateDeviceTemplate mocks base method.
func (m *MockAutoPiAPIService) UnassociateDeviceTemplate(deviceID string, templateID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassociateDeviceTemplate", deviceID, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassociateDeviceTemplate indicates an expected call of UnassociateDeviceTemplate.
func (mr *MockAutoPiAPIServiceMockRecorder) UnassociateDeviceTemplate(deviceID, templateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassociateDeviceTemplate", reflect.TypeOf((*MockAutoPiAPIService)(nil).UnassociateDeviceTemplate), deviceID, templateID)
}

// UpdateJob mocks base method.
func (m *MockAutoPiAPIService) UpdateJob(ctx context.Context, jobID, newState string, result *services.AutoPiCommandResult) (*models.AutopiJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", ctx, jobID, newState, result)
	ret0, _ := ret[0].(*models.AutopiJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockAutoPiAPIServiceMockRecorder) UpdateJob(ctx, jobID, newState, result interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockAutoPiAPIService)(nil).UpdateJob), ctx, jobID, newState, result)
}
