// Code generated by MockGen. DO NOT EDIT.
// Source: smartcar_task_service.go
//
// Generated by this command:
//
//	mockgen -source smartcar_task_service.go -destination mocks/smartcar_task_service_mock.go
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	models "github.com/DIMO-Network/devices-api/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSmartcarTaskService is a mock of SmartcarTaskService interface.
type MockSmartcarTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockSmartcarTaskServiceMockRecorder
	isgomock struct{}
}

// MockSmartcarTaskServiceMockRecorder is the mock recorder for MockSmartcarTaskService.
type MockSmartcarTaskServiceMockRecorder struct {
	mock *MockSmartcarTaskService
}

// NewMockSmartcarTaskService creates a new mock instance.
func NewMockSmartcarTaskService(ctrl *gomock.Controller) *MockSmartcarTaskService {
	mock := &MockSmartcarTaskService{ctrl: ctrl}
	mock.recorder = &MockSmartcarTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmartcarTaskService) EXPECT() *MockSmartcarTaskServiceMockRecorder {
	return m.recorder
}

// StopPoll mocks base method.
func (m *MockSmartcarTaskService) StopPoll(udai *models.UserDeviceAPIIntegration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopPoll", udai)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopPoll indicates an expected call of StopPoll.
func (mr *MockSmartcarTaskServiceMockRecorder) StopPoll(udai any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopPoll", reflect.TypeOf((*MockSmartcarTaskService)(nil).StopPoll), udai)
}
