// Code generated by MockGen. DO NOT EDIT.
// Source: vincario_api_service.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	services "github.com/DIMO-Network/devices-api/internal/services"
	gomock "github.com/golang/mock/gomock"
)

// MockVincarioAPIService is a mock of VincarioAPIService interface.
type MockVincarioAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockVincarioAPIServiceMockRecorder
}

// MockVincarioAPIServiceMockRecorder is the mock recorder for MockVincarioAPIService.
type MockVincarioAPIServiceMockRecorder struct {
	mock *MockVincarioAPIService
}

// NewMockVincarioAPIService creates a new mock instance.
func NewMockVincarioAPIService(ctrl *gomock.Controller) *MockVincarioAPIService {
	mock := &MockVincarioAPIService{ctrl: ctrl}
	mock.recorder = &MockVincarioAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVincarioAPIService) EXPECT() *MockVincarioAPIServiceMockRecorder {
	return m.recorder
}

// GetMarketValuation mocks base method.
func (m *MockVincarioAPIService) GetMarketValuation(vin string) (*services.VincarioMarketValueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketValuation", vin)
	ret0, _ := ret[0].(*services.VincarioMarketValueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketValuation indicates an expected call of GetMarketValuation.
func (mr *MockVincarioAPIServiceMockRecorder) GetMarketValuation(vin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketValuation", reflect.TypeOf((*MockVincarioAPIService)(nil).GetMarketValuation), vin)
}
