name: golangci-lint
on:
  pull_request:
    branches: [ '**' ]
env:
  GOPRIVATE: github.com/DIMO-Network
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  golangci:
    runs-on: self-hosted

    name: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Checkout code
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: false
          args: --modules-download-mode=readonly --timeout=10m
