// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AftermarketDevices        string
	AutopiJobs                string
	DeviceCommandRequests     string
	ErrorCodeQueries          string
	MetaTransactionRequests   string
	NFTPrivileges             string
	PartialAftermarketDevices string
	SyntheticDevices          string
	UserDeviceAPIIntegrations string
	UserDevices               string
}{
	AftermarketDevices:        "aftermarket_devices",
	AutopiJobs:                "autopi_jobs",
	DeviceCommandRequests:     "device_command_requests",
	ErrorCodeQueries:          "error_code_queries",
	MetaTransactionRequests:   "meta_transaction_requests",
	NFTPrivileges:             "nft_privileges",
	PartialAftermarketDevices: "partial_aftermarket_devices",
	SyntheticDevices:          "synthetic_devices",
	UserDeviceAPIIntegrations: "user_device_api_integrations",
	UserDevices:               "user_devices",
}
