// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AftermarketDevices        string
	AutopiJobs                string
	DCN                       string
	DeviceCommandRequests     string
	ErrorCodeQueries          string
	Geofences                 string
	MetaTransactionRequests   string
	NFTPrivileges             string
	SyntheticDevices          string
	UserDeviceAPIIntegrations string
	UserDeviceData            string
	UserDeviceToGeofence      string
	UserDevices               string
	VehicleNFTS               string
	VerifiableCredentials     string
}{
	AftermarketDevices:        "aftermarket_devices",
	AutopiJobs:                "autopi_jobs",
	DCN:                       "dcn",
	DeviceCommandRequests:     "device_command_requests",
	ErrorCodeQueries:          "error_code_queries",
	Geofences:                 "geofences",
	MetaTransactionRequests:   "meta_transaction_requests",
	NFTPrivileges:             "nft_privileges",
	SyntheticDevices:          "synthetic_devices",
	UserDeviceAPIIntegrations: "user_device_api_integrations",
	UserDeviceData:            "user_device_data",
	UserDeviceToGeofence:      "user_device_to_geofence",
	UserDevices:               "user_devices",
	VehicleNFTS:               "vehicle_nfts",
	VerifiableCredentials:     "verifiable_credentials",
}
