// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AutopiJobs                string
	AutopiUnits               string
	DeviceCommandRequests     string
	ErrorCodeQueries          string
	ExternalVinData           string
	Geofences                 string
	MetaTransactionRequests   string
	NFTPrivileges             string
	TokenTransfers            string
	UserDeviceAPIIntegrations string
	UserDeviceData            string
	UserDeviceToGeofence      string
	UserDevices               string
	VehicleNFTS               string
}{
	AutopiJobs:                "autopi_jobs",
	AutopiUnits:               "autopi_units",
	DeviceCommandRequests:     "device_command_requests",
	ErrorCodeQueries:          "error_code_queries",
	ExternalVinData:           "external_vin_data",
	Geofences:                 "geofences",
	MetaTransactionRequests:   "meta_transaction_requests",
	NFTPrivileges:             "nft_privileges",
	TokenTransfers:            "token_transfers",
	UserDeviceAPIIntegrations: "user_device_api_integrations",
	UserDeviceData:            "user_device_data",
	UserDeviceToGeofence:      "user_device_to_geofence",
	UserDevices:               "user_devices",
	VehicleNFTS:               "vehicle_nfts",
}
