// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// PartialAftermarketDevice is an object representing the database table.
type PartialAftermarketDevice struct {
	TokenID             types.Decimal `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	ManufacturerTokenID types.Decimal `boil:"manufacturer_token_id" json:"manufacturer_token_id" toml:"manufacturer_token_id" yaml:"manufacturer_token_id"`
	EthereumAddress     []byte        `boil:"ethereum_address" json:"ethereum_address" toml:"ethereum_address" yaml:"ethereum_address"`

	R *partialAftermarketDeviceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L partialAftermarketDeviceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PartialAftermarketDeviceColumns = struct {
	TokenID             string
	ManufacturerTokenID string
	EthereumAddress     string
}{
	TokenID:             "token_id",
	ManufacturerTokenID: "manufacturer_token_id",
	EthereumAddress:     "ethereum_address",
}

var PartialAftermarketDeviceTableColumns = struct {
	TokenID             string
	ManufacturerTokenID string
	EthereumAddress     string
}{
	TokenID:             "partial_aftermarket_devices.token_id",
	ManufacturerTokenID: "partial_aftermarket_devices.manufacturer_token_id",
	EthereumAddress:     "partial_aftermarket_devices.ethereum_address",
}

// Generated where

var PartialAftermarketDeviceWhere = struct {
	TokenID             whereHelpertypes_Decimal
	ManufacturerTokenID whereHelpertypes_Decimal
	EthereumAddress     whereHelper__byte
}{
	TokenID:             whereHelpertypes_Decimal{field: "\"devices_api\".\"partial_aftermarket_devices\".\"token_id\""},
	ManufacturerTokenID: whereHelpertypes_Decimal{field: "\"devices_api\".\"partial_aftermarket_devices\".\"manufacturer_token_id\""},
	EthereumAddress:     whereHelper__byte{field: "\"devices_api\".\"partial_aftermarket_devices\".\"ethereum_address\""},
}

// PartialAftermarketDeviceRels is where relationship names are stored.
var PartialAftermarketDeviceRels = struct {
}{}

// partialAftermarketDeviceR is where relationships are stored.
type partialAftermarketDeviceR struct {
}

// NewStruct creates a new relationship struct
func (*partialAftermarketDeviceR) NewStruct() *partialAftermarketDeviceR {
	return &partialAftermarketDeviceR{}
}

// partialAftermarketDeviceL is where Load methods for each relationship are stored.
type partialAftermarketDeviceL struct{}

var (
	partialAftermarketDeviceAllColumns            = []string{"token_id", "manufacturer_token_id", "ethereum_address"}
	partialAftermarketDeviceColumnsWithoutDefault = []string{"token_id", "manufacturer_token_id", "ethereum_address"}
	partialAftermarketDeviceColumnsWithDefault    = []string{}
	partialAftermarketDevicePrimaryKeyColumns     = []string{"token_id"}
	partialAftermarketDeviceGeneratedColumns      = []string{}
)

type (
	// PartialAftermarketDeviceSlice is an alias for a slice of pointers to PartialAftermarketDevice.
	// This should almost always be used instead of []PartialAftermarketDevice.
	PartialAftermarketDeviceSlice []*PartialAftermarketDevice
	// PartialAftermarketDeviceHook is the signature for custom PartialAftermarketDevice hook methods
	PartialAftermarketDeviceHook func(context.Context, boil.ContextExecutor, *PartialAftermarketDevice) error

	partialAftermarketDeviceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	partialAftermarketDeviceType                 = reflect.TypeOf(&PartialAftermarketDevice{})
	partialAftermarketDeviceMapping              = queries.MakeStructMapping(partialAftermarketDeviceType)
	partialAftermarketDevicePrimaryKeyMapping, _ = queries.BindMapping(partialAftermarketDeviceType, partialAftermarketDeviceMapping, partialAftermarketDevicePrimaryKeyColumns)
	partialAftermarketDeviceInsertCacheMut       sync.RWMutex
	partialAftermarketDeviceInsertCache          = make(map[string]insertCache)
	partialAftermarketDeviceUpdateCacheMut       sync.RWMutex
	partialAftermarketDeviceUpdateCache          = make(map[string]updateCache)
	partialAftermarketDeviceUpsertCacheMut       sync.RWMutex
	partialAftermarketDeviceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var partialAftermarketDeviceAfterSelectHooks []PartialAftermarketDeviceHook

var partialAftermarketDeviceBeforeInsertHooks []PartialAftermarketDeviceHook
var partialAftermarketDeviceAfterInsertHooks []PartialAftermarketDeviceHook

var partialAftermarketDeviceBeforeUpdateHooks []PartialAftermarketDeviceHook
var partialAftermarketDeviceAfterUpdateHooks []PartialAftermarketDeviceHook

var partialAftermarketDeviceBeforeDeleteHooks []PartialAftermarketDeviceHook
var partialAftermarketDeviceAfterDeleteHooks []PartialAftermarketDeviceHook

var partialAftermarketDeviceBeforeUpsertHooks []PartialAftermarketDeviceHook
var partialAftermarketDeviceAfterUpsertHooks []PartialAftermarketDeviceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PartialAftermarketDevice) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PartialAftermarketDevice) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PartialAftermarketDevice) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PartialAftermarketDevice) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PartialAftermarketDevice) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PartialAftermarketDevice) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PartialAftermarketDevice) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PartialAftermarketDevice) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PartialAftermarketDevice) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range partialAftermarketDeviceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPartialAftermarketDeviceHook registers your hook function for all future operations.
func AddPartialAftermarketDeviceHook(hookPoint boil.HookPoint, partialAftermarketDeviceHook PartialAftermarketDeviceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		partialAftermarketDeviceAfterSelectHooks = append(partialAftermarketDeviceAfterSelectHooks, partialAftermarketDeviceHook)
	case boil.BeforeInsertHook:
		partialAftermarketDeviceBeforeInsertHooks = append(partialAftermarketDeviceBeforeInsertHooks, partialAftermarketDeviceHook)
	case boil.AfterInsertHook:
		partialAftermarketDeviceAfterInsertHooks = append(partialAftermarketDeviceAfterInsertHooks, partialAftermarketDeviceHook)
	case boil.BeforeUpdateHook:
		partialAftermarketDeviceBeforeUpdateHooks = append(partialAftermarketDeviceBeforeUpdateHooks, partialAftermarketDeviceHook)
	case boil.AfterUpdateHook:
		partialAftermarketDeviceAfterUpdateHooks = append(partialAftermarketDeviceAfterUpdateHooks, partialAftermarketDeviceHook)
	case boil.BeforeDeleteHook:
		partialAftermarketDeviceBeforeDeleteHooks = append(partialAftermarketDeviceBeforeDeleteHooks, partialAftermarketDeviceHook)
	case boil.AfterDeleteHook:
		partialAftermarketDeviceAfterDeleteHooks = append(partialAftermarketDeviceAfterDeleteHooks, partialAftermarketDeviceHook)
	case boil.BeforeUpsertHook:
		partialAftermarketDeviceBeforeUpsertHooks = append(partialAftermarketDeviceBeforeUpsertHooks, partialAftermarketDeviceHook)
	case boil.AfterUpsertHook:
		partialAftermarketDeviceAfterUpsertHooks = append(partialAftermarketDeviceAfterUpsertHooks, partialAftermarketDeviceHook)
	}
}

// One returns a single partialAftermarketDevice record from the query.
func (q partialAftermarketDeviceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PartialAftermarketDevice, error) {
	o := &PartialAftermarketDevice{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for partial_aftermarket_devices")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PartialAftermarketDevice records from the query.
func (q partialAftermarketDeviceQuery) All(ctx context.Context, exec boil.ContextExecutor) (PartialAftermarketDeviceSlice, error) {
	var o []*PartialAftermarketDevice

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PartialAftermarketDevice slice")
	}

	if len(partialAftermarketDeviceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PartialAftermarketDevice records in the query.
func (q partialAftermarketDeviceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count partial_aftermarket_devices rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q partialAftermarketDeviceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if partial_aftermarket_devices exists")
	}

	return count > 0, nil
}

// PartialAftermarketDevices retrieves all the records using an executor.
func PartialAftermarketDevices(mods ...qm.QueryMod) partialAftermarketDeviceQuery {
	mods = append(mods, qm.From("\"devices_api\".\"partial_aftermarket_devices\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"devices_api\".\"partial_aftermarket_devices\".*"})
	}

	return partialAftermarketDeviceQuery{q}
}

// FindPartialAftermarketDevice retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPartialAftermarketDevice(ctx context.Context, exec boil.ContextExecutor, tokenID types.Decimal, selectCols ...string) (*PartialAftermarketDevice, error) {
	partialAftermarketDeviceObj := &PartialAftermarketDevice{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"devices_api\".\"partial_aftermarket_devices\" where \"token_id\"=$1", sel,
	)

	q := queries.Raw(query, tokenID)

	err := q.Bind(ctx, exec, partialAftermarketDeviceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from partial_aftermarket_devices")
	}

	if err = partialAftermarketDeviceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return partialAftermarketDeviceObj, err
	}

	return partialAftermarketDeviceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PartialAftermarketDevice) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no partial_aftermarket_devices provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(partialAftermarketDeviceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	partialAftermarketDeviceInsertCacheMut.RLock()
	cache, cached := partialAftermarketDeviceInsertCache[key]
	partialAftermarketDeviceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			partialAftermarketDeviceAllColumns,
			partialAftermarketDeviceColumnsWithDefault,
			partialAftermarketDeviceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(partialAftermarketDeviceType, partialAftermarketDeviceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(partialAftermarketDeviceType, partialAftermarketDeviceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"devices_api\".\"partial_aftermarket_devices\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"devices_api\".\"partial_aftermarket_devices\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into partial_aftermarket_devices")
	}

	if !cached {
		partialAftermarketDeviceInsertCacheMut.Lock()
		partialAftermarketDeviceInsertCache[key] = cache
		partialAftermarketDeviceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PartialAftermarketDevice.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PartialAftermarketDevice) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	partialAftermarketDeviceUpdateCacheMut.RLock()
	cache, cached := partialAftermarketDeviceUpdateCache[key]
	partialAftermarketDeviceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			partialAftermarketDeviceAllColumns,
			partialAftermarketDevicePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update partial_aftermarket_devices, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"devices_api\".\"partial_aftermarket_devices\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, partialAftermarketDevicePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(partialAftermarketDeviceType, partialAftermarketDeviceMapping, append(wl, partialAftermarketDevicePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update partial_aftermarket_devices row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for partial_aftermarket_devices")
	}

	if !cached {
		partialAftermarketDeviceUpdateCacheMut.Lock()
		partialAftermarketDeviceUpdateCache[key] = cache
		partialAftermarketDeviceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q partialAftermarketDeviceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for partial_aftermarket_devices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for partial_aftermarket_devices")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PartialAftermarketDeviceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), partialAftermarketDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"devices_api\".\"partial_aftermarket_devices\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, partialAftermarketDevicePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in partialAftermarketDevice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all partialAftermarketDevice")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PartialAftermarketDevice) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no partial_aftermarket_devices provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(partialAftermarketDeviceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	partialAftermarketDeviceUpsertCacheMut.RLock()
	cache, cached := partialAftermarketDeviceUpsertCache[key]
	partialAftermarketDeviceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			partialAftermarketDeviceAllColumns,
			partialAftermarketDeviceColumnsWithDefault,
			partialAftermarketDeviceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			partialAftermarketDeviceAllColumns,
			partialAftermarketDevicePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert partial_aftermarket_devices, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(partialAftermarketDevicePrimaryKeyColumns))
			copy(conflict, partialAftermarketDevicePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"devices_api\".\"partial_aftermarket_devices\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(partialAftermarketDeviceType, partialAftermarketDeviceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(partialAftermarketDeviceType, partialAftermarketDeviceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert partial_aftermarket_devices")
	}

	if !cached {
		partialAftermarketDeviceUpsertCacheMut.Lock()
		partialAftermarketDeviceUpsertCache[key] = cache
		partialAftermarketDeviceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PartialAftermarketDevice record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PartialAftermarketDevice) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PartialAftermarketDevice provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), partialAftermarketDevicePrimaryKeyMapping)
	sql := "DELETE FROM \"devices_api\".\"partial_aftermarket_devices\" WHERE \"token_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from partial_aftermarket_devices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for partial_aftermarket_devices")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q partialAftermarketDeviceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no partialAftermarketDeviceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from partial_aftermarket_devices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for partial_aftermarket_devices")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PartialAftermarketDeviceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(partialAftermarketDeviceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), partialAftermarketDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"devices_api\".\"partial_aftermarket_devices\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, partialAftermarketDevicePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from partialAftermarketDevice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for partial_aftermarket_devices")
	}

	if len(partialAftermarketDeviceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PartialAftermarketDevice) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPartialAftermarketDevice(ctx, exec, o.TokenID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PartialAftermarketDeviceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PartialAftermarketDeviceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), partialAftermarketDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"devices_api\".\"partial_aftermarket_devices\".* FROM \"devices_api\".\"partial_aftermarket_devices\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, partialAftermarketDevicePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PartialAftermarketDeviceSlice")
	}

	*o = slice

	return nil
}

// PartialAftermarketDeviceExists checks if the PartialAftermarketDevice row exists.
func PartialAftermarketDeviceExists(ctx context.Context, exec boil.ContextExecutor, tokenID types.Decimal) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"devices_api\".\"partial_aftermarket_devices\" where \"token_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tokenID)
	}
	row := exec.QueryRowContext(ctx, sql, tokenID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if partial_aftermarket_devices exists")
	}

	return exists, nil
}

// Exists checks if the PartialAftermarketDevice row exists.
func (o *PartialAftermarketDevice) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PartialAftermarketDeviceExists(ctx, exec, o.TokenID)
}
