// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// VehicleNFT is an object representing the database table.
type VehicleNFT struct {
	UserDeviceID  null.String       `boil:"user_device_id" json:"user_device_id,omitempty" toml:"user_device_id" yaml:"user_device_id,omitempty"`
	MintRequestID null.String       `boil:"mint_request_id" json:"mint_request_id,omitempty" toml:"mint_request_id" yaml:"mint_request_id,omitempty"`
	TokenID       types.NullDecimal `boil:"token_id" json:"token_id,omitempty" toml:"token_id" yaml:"token_id,omitempty"`
	ClaimID       null.String       `boil:"claim_id" json:"claim_id,omitempty" toml:"claim_id" yaml:"claim_id,omitempty"`
	OwnerAddress  null.Bytes        `boil:"owner_address" json:"owner_address,omitempty" toml:"owner_address" yaml:"owner_address,omitempty"`
	Vin           null.String       `boil:"vin" json:"vin,omitempty" toml:"vin" yaml:"vin,omitempty"`
}

var VehicleNFTColumns = struct {
	UserDeviceID  string
	MintRequestID string
	TokenID       string
	ClaimID       string
	OwnerAddress  string
	Vin           string
}{
	UserDeviceID:  "user_device_id",
	MintRequestID: "mint_request_id",
	TokenID:       "token_id",
	ClaimID:       "claim_id",
	OwnerAddress:  "owner_address",
	Vin:           "vin",
}

var VehicleNFTTableColumns = struct {
	UserDeviceID  string
	MintRequestID string
	TokenID       string
	ClaimID       string
	OwnerAddress  string
	Vin           string
}{
	UserDeviceID:  "vehicle_nfts.user_device_id",
	MintRequestID: "vehicle_nfts.mint_request_id",
	TokenID:       "vehicle_nfts.token_id",
	ClaimID:       "vehicle_nfts.claim_id",
	OwnerAddress:  "vehicle_nfts.owner_address",
	Vin:           "vehicle_nfts.vin",
}

// Generated where

var VehicleNFTWhere = struct {
	UserDeviceID  whereHelpernull_String
	MintRequestID whereHelpernull_String
	TokenID       whereHelpertypes_NullDecimal
	ClaimID       whereHelpernull_String
	OwnerAddress  whereHelpernull_Bytes
	Vin           whereHelpernull_String
}{
	UserDeviceID:  whereHelpernull_String{field: "\"devices_api\".\"vehicle_nfts\".\"user_device_id\""},
	MintRequestID: whereHelpernull_String{field: "\"devices_api\".\"vehicle_nfts\".\"mint_request_id\""},
	TokenID:       whereHelpertypes_NullDecimal{field: "\"devices_api\".\"vehicle_nfts\".\"token_id\""},
	ClaimID:       whereHelpernull_String{field: "\"devices_api\".\"vehicle_nfts\".\"claim_id\""},
	OwnerAddress:  whereHelpernull_Bytes{field: "\"devices_api\".\"vehicle_nfts\".\"owner_address\""},
	Vin:           whereHelpernull_String{field: "\"devices_api\".\"vehicle_nfts\".\"vin\""},
}

var (
	vehicleNFTAllColumns            = []string{"user_device_id", "mint_request_id", "token_id", "claim_id", "owner_address", "vin"}
	vehicleNFTColumnsWithoutDefault = []string{}
	vehicleNFTColumnsWithDefault    = []string{"user_device_id", "mint_request_id", "token_id", "claim_id", "owner_address", "vin"}
	vehicleNFTPrimaryKeyColumns     = []string{}
	vehicleNFTGeneratedColumns      = []string{}
)

type (
	// VehicleNFTSlice is an alias for a slice of pointers to VehicleNFT.
	// This should almost always be used instead of []VehicleNFT.
	VehicleNFTSlice []*VehicleNFT
	// VehicleNFTHook is the signature for custom VehicleNFT hook methods
	VehicleNFTHook func(context.Context, boil.ContextExecutor, *VehicleNFT) error

	vehicleNFTQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vehicleNFTType           = reflect.TypeOf(&VehicleNFT{})
	vehicleNFTMapping        = queries.MakeStructMapping(vehicleNFTType)
	vehicleNFTInsertCacheMut sync.RWMutex
	vehicleNFTInsertCache    = make(map[string]insertCache)
	vehicleNFTUpdateCacheMut sync.RWMutex
	vehicleNFTUpdateCache    = make(map[string]updateCache)
	vehicleNFTUpsertCacheMut sync.RWMutex
	vehicleNFTUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var vehicleNFTAfterSelectMu sync.Mutex
var vehicleNFTAfterSelectHooks []VehicleNFTHook

var vehicleNFTBeforeInsertMu sync.Mutex
var vehicleNFTBeforeInsertHooks []VehicleNFTHook
var vehicleNFTAfterInsertMu sync.Mutex
var vehicleNFTAfterInsertHooks []VehicleNFTHook

var vehicleNFTBeforeUpsertMu sync.Mutex
var vehicleNFTBeforeUpsertHooks []VehicleNFTHook
var vehicleNFTAfterUpsertMu sync.Mutex
var vehicleNFTAfterUpsertHooks []VehicleNFTHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VehicleNFT) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleNFTAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VehicleNFT) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleNFTBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VehicleNFT) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleNFTAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VehicleNFT) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleNFTBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VehicleNFT) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleNFTAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVehicleNFTHook registers your hook function for all future operations.
func AddVehicleNFTHook(hookPoint boil.HookPoint, vehicleNFTHook VehicleNFTHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		vehicleNFTAfterSelectMu.Lock()
		vehicleNFTAfterSelectHooks = append(vehicleNFTAfterSelectHooks, vehicleNFTHook)
		vehicleNFTAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		vehicleNFTBeforeInsertMu.Lock()
		vehicleNFTBeforeInsertHooks = append(vehicleNFTBeforeInsertHooks, vehicleNFTHook)
		vehicleNFTBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		vehicleNFTAfterInsertMu.Lock()
		vehicleNFTAfterInsertHooks = append(vehicleNFTAfterInsertHooks, vehicleNFTHook)
		vehicleNFTAfterInsertMu.Unlock()
	case boil.BeforeUpsertHook:
		vehicleNFTBeforeUpsertMu.Lock()
		vehicleNFTBeforeUpsertHooks = append(vehicleNFTBeforeUpsertHooks, vehicleNFTHook)
		vehicleNFTBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		vehicleNFTAfterUpsertMu.Lock()
		vehicleNFTAfterUpsertHooks = append(vehicleNFTAfterUpsertHooks, vehicleNFTHook)
		vehicleNFTAfterUpsertMu.Unlock()
	}
}

// One returns a single vehicleNFT record from the query.
func (q vehicleNFTQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VehicleNFT, error) {
	o := &VehicleNFT{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vehicle_nfts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VehicleNFT records from the query.
func (q vehicleNFTQuery) All(ctx context.Context, exec boil.ContextExecutor) (VehicleNFTSlice, error) {
	var o []*VehicleNFT

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VehicleNFT slice")
	}

	if len(vehicleNFTAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VehicleNFT records in the query.
func (q vehicleNFTQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vehicle_nfts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vehicleNFTQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vehicle_nfts exists")
	}

	return count > 0, nil
}

// VehicleNFTS retrieves all the records using an executor.
func VehicleNFTS(mods ...qm.QueryMod) vehicleNFTQuery {
	mods = append(mods, qm.From("\"devices_api\".\"vehicle_nfts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"devices_api\".\"vehicle_nfts\".*"})
	}

	return vehicleNFTQuery{q}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VehicleNFT) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vehicle_nfts provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleNFTColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vehicleNFTInsertCacheMut.RLock()
	cache, cached := vehicleNFTInsertCache[key]
	vehicleNFTInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vehicleNFTAllColumns,
			vehicleNFTColumnsWithDefault,
			vehicleNFTColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vehicleNFTType, vehicleNFTMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vehicleNFTType, vehicleNFTMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"devices_api\".\"vehicle_nfts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"devices_api\".\"vehicle_nfts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vehicle_nfts")
	}

	if !cached {
		vehicleNFTInsertCacheMut.Lock()
		vehicleNFTInsertCache[key] = cache
		vehicleNFTInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VehicleNFT) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no vehicle_nfts provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleNFTColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vehicleNFTUpsertCacheMut.RLock()
	cache, cached := vehicleNFTUpsertCache[key]
	vehicleNFTUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vehicleNFTAllColumns,
			vehicleNFTColumnsWithDefault,
			vehicleNFTColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vehicleNFTAllColumns,
			vehicleNFTPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vehicle_nfts, could not build update column list")
		}

		ret := strmangle.SetComplement(vehicleNFTAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vehicleNFTPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert vehicle_nfts, could not build conflict column list")
			}

			conflict = make([]string, len(vehicleNFTPrimaryKeyColumns))
			copy(conflict, vehicleNFTPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"devices_api\".\"vehicle_nfts\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vehicleNFTType, vehicleNFTMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vehicleNFTType, vehicleNFTMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vehicle_nfts")
	}

	if !cached {
		vehicleNFTUpsertCacheMut.Lock()
		vehicleNFTUpsertCache[key] = cache
		vehicleNFTUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
